### Мы имеем таблицу с продажами пленок (одна строка - продажа одной пленки). Переделаем эту таблицу в формат (одна строка - дата, станция и количество пленок, которое продала эта станция в эту дату)

In [45]:
from tarfile import data_filter

import pandas as pd


sales_initial = pd.read_csv('../../data/initial_data/ps_stats_initial.csv', parse_dates=['created', 'cut_time'])

In [52]:
sales_initial

,id,created,cut_time,film_size,film_type,sale_type,time_zone,element_id,station_id,tz_offset,created_local
0,1426826,2026-09-16 08:33:01.203202,2026-09-16 11:32:58.067,PHONE,GLOSS,SALE,GMT+3:00,18828.0,2417.0,0 days 03:00:00,2026-09-16 11:33:01.203202
1,1426825,2026-09-16 08:32:53.050035,2026-09-16 11:32:50.449,PHONE,MATE,SALE,GMT+3:00,15795.0,2854.0,0 days 03:00:00,2026-09-16 11:32:53.050035
2,1426824,2026-09-16 08:31:40.230850,2026-09-16 13:31:40.030,PHONE,MATE,SALE,GMT+5:00,18268.0,438.0,0 days 05:00:00,2026-09-16 13:31:40.230850
3,1426823,2026-09-16 08:30:57.475055,2026-09-16 15:30:56.323,PHONE,MATE,DEFECT,GMT+7:00,16009.0,2265.0,0 days 07:00:00,2026-09-16 15:30:57.475055
4,1426822,2026-09-16 08:30:42.547585,2026-09-16 11:30:41.074,WATCH,GLOSS,SALE,GMT+3:00,17191.0,2224.0,0 days 03:00:00,2026-09-16 11:30:42.547585
...,...,...,...,...,...,...,...,...,...,...,...
1186807,240028,2023-07-27 13:15:28.000000,2023-07-27 07:15:25.918,PHONE,GLOSS,DEFECT,GMT 3:00,NaN,1.0,0 days 03:00:00,2023-07-27 16:15:28.000000
1186808,240027,2023-07-27 13:11:28.000000,2023-07-27 07:11:25.334,PHONE,GLOSS,DEFECT,GMT 5:00,NaN,586.0,0 days 05:00:00,2023-07-27 18:11:28.000000
1186809,240026,2023-07-26 23:50:06.000000,2023-07-26 15:22:41.211,LAPTOP,GLOSS,SALE,GMT 3:00,NaN,1.0,0 days 03:00:00,2023-07-27 02:50:06.000000
1186810,240025,2023-07-26 23:49:04.000000,2023-07-26 15:22:41.222,LAPTOP,GLOSS,SALE,GMT 3:00,NaN,1.0,0 days 03:00:00,2023-07-27 02:49:04.000000
1186811,240024,2023-07-26 23:43:23.000000,2023-07-26 15:22:41.233,LAPTOP,GLOSS,SALE,GMT 3:00,NaN,1.0,0 days 03:00:00,2023-07-27 02:43:23.000000

In [47]:
import re
import pandas as pd

def parse_tz_offset(tz_str):
    # ищем знак (опционально), часы и минуты
    match = re.search(r'GMT\s*([+-]?)(\d+):(\d+)', tz_str)
    if not match:
        return pd.Timedelta(0)
    sign, hours, minutes = match.groups()
    sign = -1 if sign == '-' else 1
    return pd.Timedelta(hours=int(hours), minutes=int(minutes)) * sign

sales_initial['tz_offset'] = sales_initial['time_zone'].apply(parse_tz_offset)
sales_initial['created_local'] = sales_initial['created'] + sales_initial['tz_offset']

In [48]:
sales_initial

,id,created,cut_time,film_size,film_type,sale_type,time_zone,element_id,station_id,tz_offset,created_local
0,1426826,2026-09-16 08:33:01.203202,2026-09-16 11:32:58.067,PHONE,GLOSS,SALE,GMT+3:00,18828.0,2417.0,0 days 03:00:00,2026-09-16 11:33:01.203202
1,1426825,2026-09-16 08:32:53.050035,2026-09-16 11:32:50.449,PHONE,MATE,SALE,GMT+3:00,15795.0,2854.0,0 days 03:00:00,2026-09-16 11:32:53.050035
2,1426824,2026-09-16 08:31:40.230850,2026-09-16 13:31:40.030,PHONE,MATE,SALE,GMT+5:00,18268.0,438.0,0 days 05:00:00,2026-09-16 13:31:40.230850
3,1426823,2026-09-16 08:30:57.475055,2026-09-16 15:30:56.323,PHONE,MATE,DEFECT,GMT+7:00,16009.0,2265.0,0 days 07:00:00,2026-09-16 15:30:57.475055
4,1426822,2026-09-16 08:30:42.547585,2026-09-16 11:30:41.074,WATCH,GLOSS,SALE,GMT+3:00,17191.0,2224.0,0 days 03:00:00,2026-09-16 11:30:42.547585
...,...,...,...,...,...,...,...,...,...,...,...
1186807,240028,2023-07-27 13:15:28.000000,2023-07-27 07:15:25.918,PHONE,GLOSS,DEFECT,GMT 3:00,NaN,1.0,0 days 03:00:00,2023-07-27 16:15:28.000000
1186808,240027,2023-07-27 13:11:28.000000,2023-07-27 07:11:25.334,PHONE,GLOSS,DEFECT,GMT 5:00,NaN,586.0,0 days 05:00:00,2023-07-27 18:11:28.000000
1186809,240026,2023-07-26 23:50:06.000000,2023-07-26 15:22:41.211,LAPTOP,GLOSS,SALE,GMT 3:00,NaN,1.0,0 days 03:00:00,2023-07-27 02:50:06.000000
1186810,240025,2023-07-26 23:49:04.000000,2023-07-26 15:22:41.222,LAPTOP,GLOSS,SALE,GMT 3:00,NaN,1.0,0 days 03:00:00,2023-07-27 02:49:04.000000
1186811,240024,2023-07-26 23:43:23.000000,2023-07-26 15:22:41.233,LAPTOP,GLOSS,SALE,GMT 3:00,NaN,1.0,0 days 03:00:00,2023-07-27 02:43:23.000000

In [49]:
sales_initial.info()

<class 'pandas.DataFrame'>
RangeIndex: 1186812 entries, 0 to 1186811
Data columns (total 11 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   id             1186812 non-null  int64
 1   created        1186812 non-null  datetime64[us]
 2   cut_time       1186812 non-null  datetime64[us]
 3   film_size      1186812 non-null  str
 4   film_type      1186812 non-null  str
 5   sale_type      1186812 non-null  str
 6   time_zone      1186812 non-null  str
 7   element_id     919061 non-null   float64
 8   station_id     1186757 non-null  float64
 9   tz_offset      1186812 non-null  timedelta64[us]
 10  created_local  1186812 non-null  datetime64[us]
dtypes: datetime64[us](3), float64(2), int64(1), str(4), timedelta64[us](1)
memory usage: 99.6 MB

In [51]:
sales = sales_initial.copy()
sales = sales.drop(['id', 'created', 'film_size', 'film_type', 'time_zone', 'element_id', 'tz_offset'], axis=1)
sales = sales[sales['sale_type'] == 'SALE']
sales['date'] = sales['created_local'].dt.date
sales = sales.drop(['cut_time', 'sale_type', 'created_local'], axis=1)
sales['daily_sales_count'] = sales.groupby(['station_id', 'date'])['date'].transform('count')
sales = sales.drop_duplicates().sort_values(by=['date', 'station_id']).reset_index(drop=True)

sales

        station_id        date  daily_sales_count
0              1.0  2023-07-27                4.0
1           1531.0  2023-07-27                2.0
2              1.0  2023-07-28                3.0
3            287.0  2023-07-29                3.0
4            340.0  2023-07-29                2.0
...            ...         ...                ...
513646      3918.0  2026-09-16                1.0
513647      3930.0  2026-09-16                1.0
513648      3974.0  2026-09-16                1.0
513649      4001.0  2026-09-16                2.0
513650      4012.0  2026-09-16                4.0

[513651 rows x 3 columns]

### Известно, что некоторые станции носят технический и тестовый характер, поэтому их стоит исключить

In [ ]:
stations_to_delete = {
    495, 1283, 1288, 1800, 1802, 1803, 1822, 1880, 1881, 1934,
    1936, 1947, 1950, 1951, 1952, 1954, 1971, 2224, 2242, 2243,
    2247, 2342, 2343, 2345, 2392, 2433, 2450, 2562, 2593, 2760,
    2902, 2903, 2904, 2910, 3267, 3268, 3270, 3300, 3353, 3354,
    3366, 3441, 3488, 3494, 3511, 3554, 3577, 3585, 3619, 3630,
    3636, 3637, 3638, 1227, 1538, 1539, 1540, 1805, 1824, 1826,
    1828, 1926, 1957, 1972, 2254, 3316, 3361, 3508, 3602, 1801, 1
}

sales = sales[~sales['station_id'].isin(stations_to_delete)]

### Посмотрим на распределение того, сколько в день продают пленок (нам станет ясно, что есть выбросы, которые стоит исключить)

In [ ]:
sales['daily_sales_count'].value_counts()

In [ ]:
sales = sales[sales['daily_sales_count'] <= 50]

### Теперь остается разбить данные на train and test, в качестве тестовой выборки будем использовать август 2026 года.

In [ ]:
sales['station_id'] = sales['station_id'].astype(int)

In [ ]:
# train_sales = sales[sales['date'] <= pd.to_datetime('2026-07-31').date()]
# test_sales = sales[sales['date'] > pd.to_datetime('2026-07-31').date()]

In [ ]:
sales.to_csv('../../data/Cleared_data/sales.csv', index=False)